--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/12/2020 5:46:35 PM
-- Server version: 8.0.20
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE digital_signage;

--
-- Drop table `canvas`
--
DROP TABLE IF EXISTS canvas;

--
-- Drop table `canvas_division`
--
DROP TABLE IF EXISTS canvas_division;

--
-- Drop table `frame`
--
DROP TABLE IF EXISTS frame;

--
-- Drop table `panel`
--
DROP TABLE IF EXISTS panel;

--
-- Drop table `screen`
--
DROP TABLE IF EXISTS screen;

--
-- Set default database
--
USE digital_signage;

--
-- Create table `screen`
--
CREATE TABLE screen (
  id INT NOT NULL AUTO_INCREMENT,
  mac_address VARCHAR(255) DEFAULT NULL,
  name VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  canvas_id INT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `panel`
--
CREATE TABLE panel (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Một vùng không gian hiển thị trong Canvas chứa 1 or nhiều Frame';

--
-- Create table `frame`
--
CREATE TABLE frame (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  type VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `canvas_division`
--
CREATE TABLE canvas_division (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  width INT DEFAULT NULL,
  height INT DEFAULT NULL,
  top INT DEFAULT NULL,
  `left` INT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `canvas`
--
CREATE TABLE canvas (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  width INT DEFAULT NULL,
  heigth INT DEFAULT NULL,
  top INT DEFAULT NULL,
  `left` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Định nghĩa kích thước khoảng trống để hiển thị nội dung';

-- 
-- Dumping data for table screen
--
-- Table digital_signage.screen does not contain any data (it is empty)

-- 
-- Dumping data for table panel
--
-- Table digital_signage.panel does not contain any data (it is empty)

-- 
-- Dumping data for table frame
--
-- Table digital_signage.frame does not contain any data (it is empty)

-- 
-- Dumping data for table canvas_division
--
-- Table digital_signage.canvas_division does not contain any data (it is empty)

-- 
-- Dumping data for table canvas
--
-- Table digital_signage.canvas does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;